import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "../../components/Navbar";
import Footer from "../../components/Footer";
import { Toaster } from "react-hot-toast";
import AuthProvider from "@/context/AuthProvider";

export const metadata = {
  title: "EduSoft",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`flex flex-col min-h-screen antialiased`}>
        <AuthProvider>
          <NavBar />
          <main className="flex-grow">{children}</main>
          <Footer />
          <Toaster />
        </AuthProvider>
      </body>
    </html>
  );
}
